# Site settings
title: FinTech Ecosystem
description: > # this means to ignore newlines until "baseurl:"
  Ontological Modelling of the FinTech Ecosystem, a Source of Solutions to Operational Risks
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fintechecosystem.github.io/" # the base hostname & protocol for your site

# Plugins
gems:
  - jekyll-sitemap

# Handling Reading
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - Dockerfile
  - docker-compose
  - .travis.yml

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: "<!--more-->"

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

# Outputting
permalink: :year/:month/:day/:title/
timezone: Europe/Dublin
